export const LOAD_FILTERED_STATS = 'LOAD_FILTERED_STATS';
export const LOAD_UNFILTERED_STATS = 'LOAD_UNFILTERED_STATS';
export const LOAD_CRITERIA_DATA_MODEL = 'LOAD_CRITERIA_DATA_MODEL';
export const LOAD_FEATURE_FLAGS = 'LOAD_FEATURE_FLAGS';

export const SET_ACTIVE_FILTERS = 'SET_ACTIVE_FILTERS';
export const SET_ACTIVE_YMCA_SITES = 'SET_ACTIVE_YMCA_SITES';
export const SET_RESULT_LIMITS = 'SET_RESULT_LIMITS';
