version: '2'
services:
  api:
    build: api
    command: server
    ports:
      - "5000:5000"
    volumes:
      - "./api:/usr/src/app:ro"
      - "./screening-data:/data:ro"
    environment:
      SCREENING_DATA_FILE: "/data/pscr.csv"
  ui:
    build: ui
    command: run dev
    ports:
      - "8080:8080"
    volumes:
      - "./ui/src:/usr/src/app/src"
    environment:
      HOST: 0.0.0.0
    links:
      - api:api
